services:
  backend:
    build: ./simpleapi
    container_name: apitp
    networks:
      - network-app
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL= ${POSTGRES_URL}

  database:
    container_name: dbtp
    build: ./database
    networks:
      - network-app
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes :
        - volume-tp:/var/lib/postgresql/data

  httpd:
    container_name: fronttp
    build: ./front
    ports:
    - "80:80"
    networks:
      - network-app
    depends_on:
        - backend

networks:
  network-app:

volumes:
  volume-tp: